# Generated by Django 5.0.6 on 2024-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetasks',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
